//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalEconomicStandardsParser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("МКБ коды.xlsx")]
        public string MkbCodesFileName {
            get {
                return ((string)(this["MkbCodesFileName"]));
            }
            set {
                this["MkbCodesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string MkbCodesDgcodeColumn {
            get {
                return ((string)(this["MkbCodesDgcodeColumn"]));
            }
            set {
                this["MkbCodesDgcodeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string MkbCodesMkbcodeColumn {
            get {
                return ((string)(this["MkbCodesMkbcodeColumn"]));
            }
            set {
                this["MkbCodesMkbcodeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MkbCodesFirstRowWithData {
            get {
                return ((int)(this["MkbCodesFirstRowWithData"]));
            }
            set {
                this["MkbCodesFirstRowWithData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("МКБ коды")]
        public string MkbCodesSheetName {
            get {
                return ((string)(this["MkbCodesSheetName"]));
            }
            set {
                this["MkbCodesSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MESSheetName {
            get {
                return ((string)(this["MESSheetName"]));
            }
            set {
                this["MESSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MESFirstRowWithData {
            get {
                return ((int)(this["MESFirstRowWithData"]));
            }
            set {
                this["MESFirstRowWithData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("МКБ10")]
        public string MESMkbBlockName {
            get {
                return ((string)(this["MESMkbBlockName"]));
            }
            set {
                this["MESMkbBlockName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string MESMkbCodeColumn {
            get {
                return ((string)(this["MESMkbCodeColumn"]));
            }
            set {
                this["MESMkbCodeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string MESMkbNameColumn {
            get {
                return ((string)(this["MESMkbNameColumn"]));
            }
            set {
                this["MESMkbNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string MESDataMedicalServiceCodeColumn {
            get {
                return ((string)(this["MESDataMedicalServiceCodeColumn"]));
            }
            set {
                this["MESDataMedicalServiceCodeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string МESDataMedicalServiceNameColumn {
            get {
                return ((string)(this["МESDataMedicalServiceNameColumn"]));
            }
            set {
                this["МESDataMedicalServiceNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string МESDataAverageFrequencyOfGrantingColumn {
            get {
                return ((string)(this["МESDataAverageFrequencyOfGrantingColumn"]));
            }
            set {
                this["МESDataAverageFrequencyOfGrantingColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string МESDataAverageIndexOfFrequencyOfApplicationColumn {
            get {
                return ((string)(this["МESDataAverageIndexOfFrequencyOfApplicationColumn"]));
            }
            set {
                this["МESDataAverageIndexOfFrequencyOfApplicationColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string MESDataServiceNameColumn {
            get {
                return ((string)(this["MESDataServiceNameColumn"]));
            }
            set {
                this["MESDataServiceNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string MESDataCodeColumn {
            get {
                return ((string)(this["MESDataCodeColumn"]));
            }
            set {
                this["MESDataCodeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string MESDataFactColumn {
            get {
                return ((string)(this["MESDataFactColumn"]));
            }
            set {
                this["MESDataFactColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string MESDataPrepaidExpenseColumn {
            get {
                return ((string)(this["MESDataPrepaidExpenseColumn"]));
            }
            set {
                this["MESDataPrepaidExpenseColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string MESDataCountColumn {
            get {
                return ((string)(this["MESDataCountColumn"]));
            }
            set {
                this["MESDataCountColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public string MESDataAgeFromColumn {
            get {
                return ((string)(this["MESDataAgeFromColumn"]));
            }
            set {
                this["MESDataAgeFromColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K")]
        public string MESDataAgeBeforeColumn {
            get {
                return ((string)(this["MESDataAgeBeforeColumn"]));
            }
            set {
                this["MESDataAgeBeforeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string MESDataDiagnosticControlColumn {
            get {
                return ((string)(this["MESDataDiagnosticControlColumn"]));
            }
            set {
                this["MESDataDiagnosticControlColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Код медицинской услуги")]
        public string MESDataBlockName {
            get {
                return ((string)(this["MESDataBlockName"]));
            }
            set {
                this["MESDataBlockName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Template_Mis.xlsx")]
        public string TemplateFileNameMis {
            get {
                return ((string)(this["TemplateFileNameMis"]));
            }
            set {
                this["TemplateFileNameMis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Template_Summary.xlsx")]
        public string TemplateFileNameSummary {
            get {
                return ((string)(this["TemplateFileNameSummary"]));
            }
            set {
                this["TemplateFileNameSummary"] = value;
            }
        }
    }
}
